# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  MyBuildNumber: '1.0.0-CI-$(Build.BuildId)'
  

steps:

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 3.0.100'
  inputs:
    packageType: sdk
    version: 3.0.100
    installationPath: $(Agent.ToolsDirectory)/dotnet

  
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'


- task: VSBuild@1
  displayName: Build
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 3.0.100'
  inputs:
    packageType: sdk
    version: 3.0.100
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: Unit Tests
  inputs:
    command: test
    projects: '**/*Test.Unit/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
    
    
- task: NuGetCommand@2
  displayName: 'Nuget Pack'
  inputs:
    command: pack
    packagesToPack: '**/KudoCode.LogicLayer.Infrastructure.csproj'
    packDestination: '$(Build.ArtifactStagingDirectory)'
    #includeReferencedProjects: false
    #versionEnvVar: '$(MyBuildNumber)'
    buildProperties: ' -Version 1.1.1.1'
